// ══════════════════════════════════════════════════════════
// Cost of Inaction — Industry Presets
// 14 industries with research-backed default amounts
// Sources: NPMA, FDA, Orkin, USDA, Joint Commission, AHLA
// ══════════════════════════════════════════════════════════

import type { IndustryPreset } from "./types";

export const INDUSTRY_PRESETS: Record<string, IndustryPreset> = {
  restaurant_food_service: {
    id: "restaurant_food_service",
    name: "Restaurant / Food Service",
    icon: "🍽️",
    color: "#E9C46A",
    description: "Health code violations, closure risk, contamination, and lost business",
    categories: [
      { id: "health_violations", label: "Health Code Violations & Fines", description: "State/county fines for pest evidence during inspections", defaultAmount: 1500, icon: "⚠️",
        rationale: "Fines range $200–$2,000 per violation. NYC pest violations carry $200–$600 fines. Repeat offenses in major cities reach $2,000+. Pest issues account for 20% of health inspection scores. (FDA, local health depts)" },
      { id: "temp_closure", label: "Temporary Closure Costs", description: "Revenue lost per day of forced shutdown", defaultAmount: 5000, icon: "🚫",
        rationale: "A restaurant closure costs $500+ per day in lost revenue (Fairfax County data). Average restaurant does $1.5M/yr = ~$4,100/day. One pest sighting during inspection can trigger immediate shutdown. (MaintainIQ, local health depts)" },
      { id: "food_contamination", label: "Food Contamination & Waste", description: "Spoiled inventory, discarded prep, and wasted product", defaultAmount: 1500, icon: "🗑️",
        rationale: "Contaminated food must be discarded entirely. Average restaurant food costs run 28–35% of revenue. A single contamination event can destroy $1,000–$5,000 in inventory. (National Restaurant Association)" },
      { id: "lost_business", label: "Customer Complaints & Lost Business", description: "Customers who leave and never return", defaultAmount: 2500, icon: "👥",
        rationale: "Restaurants experience 5–9% revenue loss tied to negative cleanliness reviews online. For a $1.5M/yr restaurant, even 5% = $6,250/mo. (Harvard Business School review study)" },
      { id: "reputation", label: "Reputation Damage / Bad Reviews", description: "Online review damage impacting future revenue", defaultAmount: 2000, icon: "⭐",
        rationale: "A single one-star drop on Yelp can reduce revenue 5–9%. Pest-related reviews spread rapidly on Google and social media, destroying years of customer trust. (Harvard Business Review, Yelp economic study)" },
      { id: "turnover", label: "Employee Turnover from Conditions", description: "Cost to recruit and train replacement staff", defaultAmount: 800, icon: "🔄",
        rationale: "Restaurant employee turnover costs $2,000–$5,000 per position (Center for Hospitality Research). Unsanitary conditions accelerate departure of skilled staff." },
      { id: "emergency_treatment", label: "Emergency Extermination", description: "Reactive pest treatment at premium pricing", defaultAmount: 800, icon: "🚨",
        rationale: "Emergency/after-hours pest treatments cost 2–3x regular service rates. Average emergency restaurant treatment runs $500–$1,500. (NPMA industry data)" },
      { id: "lawsuit_liability", label: "Lawsuit / Liability Risk", description: "Legal exposure from customer illness or injury", defaultAmount: 5000, icon: "⚖️",
        rationale: "Foodborne illness lawsuits average $75,000–$150,000 in settlements. Even small claims for foreign objects in food average $5,000–$25,000. Monthly risk reserve is conservative. (Food Safety Magazine)" },
    ],
  },

  hotel_hospitality: {
    id: "hotel_hospitality",
    name: "Hotel / Hospitality",
    icon: "🏨",
    color: "#E76F51",
    description: "Guest refunds, reputation damage, and regulatory exposure",
    categories: [
      { id: "guest_refunds", label: "Guest Refunds & Comps", description: "Room refunds, free nights, and service credits", defaultAmount: 3000, icon: "💳",
        rationale: "Hotels spend avg $6,383 per bed bug incident on guest compensation, treatment, and lost revenue. Half of surveyed hotels paid avg $20,000 in guest damages. (Orkin 'Behind the Cost of Bed Bugs' report)" },
      { id: "negative_reviews", label: "Negative Online Reviews", description: "Lost bookings from pest-related reviews", defaultAmount: 5000, icon: "⭐",
        rationale: "Revenue per room decreases $38 per negative review. One bed bug report costs a 300-room business hotel ~$274,000 (Univ. of Kentucky study). Even one report reduces room value by $10/night. (ScienceDirect)" },
      { id: "room_downtime", label: "Room Downtime for Treatment", description: "Revenue loss from rooms pulled out of service", defaultAmount: 2000, icon: "🚪",
        rationale: "Treatment of a single room costs $500–$1,000 (NPMA). Rooms are offline 24–72 hours per treatment, with multiple treatments often needed. At $150/night avg, each room offline = $150–$450 in lost revenue." },
      { id: "health_violations", label: "Health Department Violations", description: "Fines and citations from inspections", defaultAmount: 2000, icon: "⚠️",
        rationale: "Hotel health violations range $200–$2,000+ per citation depending on jurisdiction. Repeat violations can trigger license review. (Local health departments)" },
      { id: "brand_damage", label: "Brand Reputation Damage", description: "Long-term impact on brand perception and bookings", defaultAmount: 8000, icon: "📉",
        rationale: "Over a 5-year period, bed bug costs to a single hotel can exceed $160,000 ($2,667/mo). Guests check bed bug registries before booking. Brand damage from viral social media posts is often irreparable. (Orkin, Nattaro Labs)" },
      { id: "staff_turnover", label: "Staff Complaints & Turnover", description: "Housekeeping and front-desk staff loss", defaultAmount: 1200, icon: "🔄",
        rationale: "Hospitality turnover costs $3,000–$5,000 per position. Housekeeping staff exposed to pests leave faster. 4 out of 5 hotels treated for bed bugs last year. (AHLA, NPMA survey)" },
      { id: "emergency_treatment", label: "Emergency Pest Treatment", description: "Urgent after-hours service at premium rates", defaultAmount: 1200, icon: "🚨",
        rationale: "Emergency hotel treatments average $800–$2,000. Heat treatments for bed bugs run $1,000–$3,000 per room. Multiple rooms often affected. (NPMA pricing data)" },
      { id: "legal_liability", label: "Legal Liability", description: "Lawsuits from guest injuries or illness", defaultAmount: 10000, icon: "⚖️",
        rationale: "Bed bug lawsuit settlements typically range $2,000–$80,000. Major verdicts have reached $2M (Ventura CA 2025) and $135K (Baltimore 2021). 68% of pest pros treated bed bugs in hotels last year. (Bed Bug Law, court records)" },
    ],
  },

  multi_family_apartment: {
    id: "multi_family_apartment",
    name: "Multi Family / Apartment",
    icon: "🏢",
    color: "#2A9D8F",
    description: "Tenant complaints, vacancies, and property value decline",
    categories: [
      { id: "tenant_turnover", label: "Tenant Complaints & Turnover", description: "Early lease breaks and lost tenants", defaultAmount: 2500, icon: "🚪",
        rationale: "Tenant turnover costs $3,000–$5,000 per unit (advertising, cleaning, lost rent during vacancy). Pest complaints are a top driver of early lease breaks. Tenants can legally break leases for habitability violations in most states. (NAA)" },
      { id: "vacancy_costs", label: "Unit Vacancy Costs", description: "Lost rent from vacant units during treatment", defaultAmount: 2000, icon: "🏚️",
        rationale: "Average apartment rent is $1,500–$2,000/mo. Units may be offline 1–7 days for treatment. Bed bug treatment requires tenant prep that can extend vacancies. (NAA, Census Bureau)" },
      { id: "emergency_treatment", label: "Emergency Treatments", description: "Reactive pest control at premium pricing", defaultAmount: 800, icon: "🚨",
        rationale: "Emergency multi-unit treatments cost 2–3x scheduled service. Bed bug heat treatment runs $1,000–$3,000 per unit. Infestations spread between units requiring multiple treatments. (NPMA)" },
      { id: "health_violations", label: "Health Code Violations", description: "Municipal fines and citations", defaultAmount: 1500, icon: "⚠️",
        rationale: "Municipal fines for habitability violations range $500–$5,000. In NYC, landlords must disclose bed bug history. 21 states have specific bed bug laws holding landlords liable. (Nolo, state statutes)" },
      { id: "property_value", label: "Property Value Decline", description: "Reduced appraisal and rental rates", defaultAmount: 3000, icon: "📉",
        rationale: "Properties with known pest histories see 3–5% reduced rental rates and lower appraisals. For a 20-unit building at $1,500/mo avg, even 3% decline = $900/mo across the portfolio. (NAA market data)" },
      { id: "legal_liability", label: "Legal Liability from Tenants", description: "Tenant lawsuits for habitability issues", defaultAmount: 5000, icon: "⚖️",
        rationale: "Tenant lawsuits for pest-related habitability violations are rising. Class actions against apartment complexes have resulted in six-figure settlements. Landlord insurance typically does NOT cover pest infestations. (Nolo, Folds Walker)" },
      { id: "repair_costs", label: "Repair Costs from Pest Damage", description: "Drywall, wiring, insulation repair", defaultAmount: 1200, icon: "🔧",
        rationale: "Rodents chew through wiring ($500–$2,000 to repair), insulation, and plumbing. Termite damage to multi-family structures averages $3,000+ per incident. Most landlord insurance excludes pest damage. (NPMA, Angi)" },
    ],
  },

  office_corporate: {
    id: "office_corporate",
    name: "Office / Corporate",
    icon: "🏢",
    color: "#264653",
    description: "Productivity loss, OSHA risk, and client impression damage",
    categories: [
      { id: "productivity_loss", label: "Employee Productivity Loss", description: "Distracted and uncomfortable staff", defaultAmount: 2500, icon: "📉",
        rationale: "Studies show pest-related complaints reduce worker productivity 5–10%. For a 20-person office at $50K avg salary, 5% productivity loss = $4,167/mo. (BOMA, workplace wellness studies)" },
      { id: "osha_risk", label: "Health Complaints & OSHA Risk", description: "Workplace safety violations and complaints", defaultAmount: 2000, icon: "⚠️",
        rationale: "OSHA penalties for workplace health violations range $1,036–$15,625 per violation. Rodent droppings and cockroach allergens trigger workplace health complaints. (OSHA penalty schedule)" },
      { id: "client_impression", label: "Client Impression Damage", description: "Lost deals from unprofessional appearance", defaultAmount: 4000, icon: "🤝",
        rationale: "A single pest sighting during a client visit can kill a deal worth tens of thousands. Professional services firms report lost contracts from office appearance issues. (BOMA surveys)" },
      { id: "emergency_treatment", label: "Emergency Pest Treatment", description: "Reactive service at premium rates", defaultAmount: 800, icon: "🚨",
        rationale: "Commercial emergency treatments cost $500–$1,500+. After-hours service for office buildings carries 2–3x premium. (NPMA industry pricing)" },
      { id: "equipment_damage", label: "Equipment / Wiring Damage", description: "Rodent damage to cables and infrastructure", defaultAmount: 1500, icon: "🔌",
        rationale: "Rodents chewing through data cables and electrical wiring cause $500–$5,000+ per incident. Can trigger fire hazards. Insurance often excludes pest damage. (NFPA fire data)" },
      { id: "lease_violations", label: "Lease Violation Penalties", description: "Landlord penalties for pest conditions", defaultAmount: 3000, icon: "📋",
        rationale: "Commercial leases often include maintenance clauses. Landlords can assess penalties or withhold security deposits for pest-related damages. Remediation charges passed to tenants. (BOMA lease standards)" },
    ],
  },

  retail_sales_floor: {
    id: "retail_sales_floor",
    name: "Retail / Sales Floor",
    icon: "🛍️",
    color: "#F4A261",
    description: "Product damage, lost sales, and brand reputation",
    categories: [
      { id: "product_damage", label: "Product Contamination & Damage", description: "Destroyed merchandise and packaging", defaultAmount: 2500, icon: "📦",
        rationale: "Stored product pests damage up to 10% of total food produced in the US. One baby food company had a $250M recall from warehouse beetles. Retail product damage from rodents/insects averages $2,000–$10,000/mo. (USDA, QA Magazine)" },
      { id: "lost_sales", label: "Customer Complaints & Lost Sales", description: "Shoppers who leave and don't return", defaultAmount: 3000, icon: "👥",
        rationale: "Customer who has a negative pest experience tells 9–15 people on average. A visible pest event causes immediate walkouts and long-term customer loss. (Customer experience research)" },
      { id: "health_violations", label: "Health Department Violations", description: "Fines from retail inspections", defaultAmount: 1500, icon: "⚠️",
        rationale: "Retail food establishment fines range $200–$2,000+ per violation. Grocery and food retailers face more frequent inspections. (FDA, local health departments)" },
      { id: "brand_damage", label: "Brand Reputation Damage", description: "Social media and review impact", defaultAmount: 4000, icon: "📉",
        rationale: "Viral pest sighting videos on social media have caused store-level sales drops of 10–20%. One bad review can cost a local business 30 customers. (ReviewTrackers data)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Reactive pest control services", defaultAmount: 800, icon: "🚨",
        rationale: "Emergency retail treatments cost $500–$2,000. Some require overnight fumigation with lost business day. (NPMA)" },
      { id: "inventory_loss", label: "Inventory Write-Offs", description: "Product that must be discarded", defaultAmount: 2000, icon: "🗑️",
        rationale: "FDA requires disposal of any food products with evidence of pest contamination. A single rodent incident can require disposal of entire sections of inventory. (FDA Food Code)" },
    ],
  },

  healthcare_medical: {
    id: "healthcare_medical",
    name: "Healthcare / Medical",
    icon: "🏥",
    color: "#457B9D",
    description: "Regulatory fines, patient safety, and accreditation risk",
    categories: [
      { id: "regulatory_fines", label: "Regulatory Violations & Fines", description: "State and federal healthcare compliance fines", defaultAmount: 10000, icon: "⚠️",
        rationale: "California state fines: up to $75K first violation, $100K second, $125K third. CMS can impose 1% Medicare payment reduction on worst-performing hospitals. 224 penalties totaling $7.7M issued to 129 CA hospitals alone. (CMS, CDPH)" },
      { id: "patient_safety", label: "Patient Safety Incidents", description: "Infection risk and patient harm exposure", defaultAmount: 12000, icon: "🏥",
        rationale: "1 in 25 US hospital patients acquires an infection during care. Treatment cost per healthcare-associated infection: $1,000–$50,000. Cockroaches carry E. coli and Salmonella, especially dangerous for immunocompromised patients. (CDC, PMC)" },
      { id: "accreditation_risk", label: "Accreditation Risk", description: "Risk of losing JCAHO or state certification", defaultAmount: 20000, icon: "📋",
        rationale: "Loss of Joint Commission accreditation means loss of Medicare/Medicaid reimbursement — devastating for any hospital. Pest management is specifically evaluated in JCAHO Environment of Care standards. (Joint Commission)" },
      { id: "lawsuit_exposure", label: "Lawsuit / Malpractice Exposure", description: "Legal claims from patients or families", defaultAmount: 20000, icon: "⚖️",
        rationale: "An IL nursing home paid $250,000 in damages after a patient was infested with maggots. 59% of bed bug infestations occur in nursing homes. Healthcare facility lawsuits for pest-related harm average $50K–$500K. (Court records, NPMA)" },
      { id: "emergency_remediation", label: "Emergency Pest Remediation", description: "Urgent treatment to maintain compliance", defaultAmount: 2000, icon: "🚨",
        rationale: "Healthcare facility pest treatments require specialized protocols due to patient safety. Costs 3–5x residential rates. Must use IPM approaches per Joint Commission standards. (EPA IPM Toolkit)" },
      { id: "reputation_damage", label: "Reputation Damage", description: "Community trust and patient referral loss", defaultAmount: 6000, icon: "📉",
        rationale: "Low patient satisfaction scores from pest encounters affect hospital ratings, referral patterns, and CMS reimbursement rates. Public health violations are reportable and searchable at hospitalinspections.org. (CMS, HCAHPS)" },
    ],
  },

  education_school: {
    id: "education_school",
    name: "Education / School",
    icon: "🏫",
    color: "#6366F1",
    description: "Parent complaints, enrollment risk, and regulatory exposure",
    categories: [
      { id: "enrollment_loss", label: "Parent Complaints & Enrollment Loss", description: "Families leaving for other schools", defaultAmount: 4000, icon: "👨‍👩‍👧",
        rationale: "Per-pupil funding averages $13,000–$16,000/yr nationally. Losing even 3–4 students = $40,000–$64,000/yr in lost funding ($3,300–$5,300/mo). Parent pest complaints spread through school community rapidly. (NCES)" },
      { id: "closure_risk", label: "Health Department Closure Risk", description: "Forced temporary closure costs", defaultAmount: 6000, icon: "🚫",
        rationale: "School closures cost districts $10,000–$50,000+ per day in logistics, lost instruction time, and emergency childcare coordination. Health departments can order immediate closure for active infestations. (Dept of Education)" },
      { id: "student_health", label: "Student Health Incidents", description: "Allergic reactions, bites, and illness", defaultAmount: 2500, icon: "🏥",
        rationale: "Cockroach allergens trigger asthma attacks in 23–60% of urban children with asthma. School-onset allergic reactions require emergency response and potential liability. (NIH, EPA)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Reactive pest control during school year", defaultAmount: 1000, icon: "🚨",
        rationale: "School pest treatments must follow EPA IPM guidelines and often require weekend/holiday scheduling at premium rates. Multi-building campuses multiply costs. (EPA IPM for Schools)" },
      { id: "regulatory_fines", label: "Regulatory Fines", description: "State education and health department fines", defaultAmount: 2000, icon: "⚠️",
        rationale: "State education agencies can impose corrective action plans and fines. Health department violations at schools carry heightened scrutiny and public reporting. (State education codes)" },
      { id: "staff_morale", label: "Staff Morale & Retention", description: "Teacher dissatisfaction and turnover", defaultAmount: 1200, icon: "🔄",
        rationale: "Teacher replacement costs $10,000–$20,000 per position. Poor building conditions rank among top reasons for teacher attrition. (Learning Policy Institute)" },
    ],
  },

  warehouse_distribution: {
    id: "warehouse_distribution",
    name: "Warehouse / Distribution",
    icon: "🏭",
    color: "#78716C",
    description: "Product recalls, failed audits, and contract loss",
    categories: [
      { id: "contamination_recalls", label: "Product Contamination & Recalls", description: "Recalled goods and disposal costs", defaultAmount: 25000, icon: "📦",
        rationale: "Median recall cost: $3M–$72.7M per firm. Gold Star Distribution recalled nearly 2,000 products in Dec 2025 due to rodent/bird contamination. Spinach recall cost industry $350M in one year. (FDA, Food Safety Magazine)" },
      { id: "failed_audits", label: "Failed Audits & Lost Contracts", description: "Client audit failures ending business relationships", defaultAmount: 15000, icon: "📋",
        rationale: "Third-party food safety audit failure (SQF, BRC) can terminate contracts worth $100K–$1M+. Grain buyers refuse delivery of contaminated product entirely. (QA Magazine, GFSI)" },
      { id: "regulatory_fines", label: "Regulatory Fines", description: "FDA, USDA, or state compliance fines", defaultAmount: 5000, icon: "⚠️",
        rationale: "FDA can issue Class I, II, or III recalls. Failure to report contamination within 24 hours is a prohibited act under federal law. Fines range $10,000–$500,000+. (FDA, FFDCA)" },
      { id: "inventory_damage", label: "Inventory Damage & Write-Offs", description: "Pest-damaged stored goods", defaultAmount: 8000, icon: "🗑️",
        rationale: "Stored product pests damage up to 10% of total US food production. One company lost $250M from warehouse beetles in baby food. Even small facilities lose thousands monthly to pest consumption. (USDA, QA Magazine)" },
      { id: "emergency_fumigation", label: "Emergency Fumigation", description: "Full-facility fumigation at premium cost", defaultAmount: 3000, icon: "🚨",
        rationale: "Full warehouse fumigation costs $2,000–$10,000+ depending on size. Facility must be shut down 24–72 hours. Lost production/shipping during downtime adds to cost. (NPMA)" },
      { id: "client_loss", label: "Client Loss from Quality Issues", description: "Contracts cancelled due to pest history", defaultAmount: 12000, icon: "📉",
        rationale: "When contamination is discovered, buyers cannot distinguish good product from bad — entire inventory lots get rejected. Single pest incident can end a 10+ year client relationship. (Food Safety Magazine)" },
    ],
  },

  church_worship: {
    id: "church_worship",
    name: "Church / House of Worship",
    icon: "⛪",
    color: "#8B5CF6",
    description: "Attendance impact, structural damage, and event disruption",
    categories: [
      { id: "attendance_drop", label: "Member Complaints & Attendance Drop", description: "Members avoiding services due to pest issues", defaultAmount: 1500, icon: "👥",
        rationale: "Average church offering per attendee is $50–$75/week. Losing 5–10 families due to pest complaints = $1,000–$3,000/mo in reduced giving. (Giving USA Foundation)" },
      { id: "structural_damage", label: "Structural Damage from Pests", description: "Wood damage, nesting, insulation destruction", defaultAmount: 2500, icon: "🔧",
        rationale: "Termite damage to US structures costs $5B annually. Older church buildings with wood framing are especially vulnerable. Average repair costs $3,000+ per incident. (Orkin, USDA)" },
      { id: "event_cancellations", label: "Event Cancellations", description: "Weddings, potlucks, and gatherings cancelled", defaultAmount: 1200, icon: "📅",
        rationale: "Churches host 3–5 events/month generating $500–$3,000 each in facility rental, donations, and fellowship income. Pest events force cancellations. (Church management data)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Reactive pest control services", defaultAmount: 600, icon: "🚨",
        rationale: "Emergency service calls for churches run $300–$1,000. Large buildings and multi-room facilities increase costs. Weekend service carries premium rates. (NPMA)" },
      { id: "food_pantry", label: "Food Pantry Contamination", description: "Donated food destroyed by pests", defaultAmount: 800, icon: "🥫",
        rationale: "Food pantries lose 5–15% of donations to pest contamination. Stored product pests infest flour, cereal, rice, and dried goods. Replacement costs for donated food fall on the church. (Feeding America)" },
      { id: "community_reputation", label: "Reputation in Community", description: "Negative community perception", defaultAmount: 2000, icon: "📉",
        rationale: "Churches rely on community trust for membership and outreach. Pest issues undermine the perception of care and stewardship. Word of mouth in congregations spreads rapidly." },
    ],
  },

  auto_dealership: {
    id: "auto_dealership",
    name: "Auto Dealership / Shop",
    icon: "🚗",
    color: "#DC2626",
    description: "Vehicle damage, customer complaints, and insurance claims",
    categories: [
      { id: "vehicle_damage", label: "Vehicle Damage from Rodents", description: "Chewed wiring, nesting, upholstery damage", defaultAmount: 4000, icon: "🚗",
        rationale: "Rodent damage to vehicle wiring costs $500–$5,000+ per vehicle to repair. Soy-based wiring in modern vehicles attracts rodents. Multiple vehicles can be damaged in a single infestation event. (AAA, consumer reports)" },
      { id: "customer_complaints", label: "Customer Complaints", description: "Buyers discovering pest evidence in vehicles", defaultAmount: 2500, icon: "👥",
        rationale: "A new car buyer finding rodent droppings or nesting material leads to immediate returns, refund demands, and online complaints that damage the dealership's reputation. (NADA dealer studies)" },
      { id: "inventory_contamination", label: "Inventory Contamination", description: "Parts and supplies damaged by pests", defaultAmount: 1500, icon: "📦",
        rationale: "Parts inventory, shop supplies, and customer vehicles stored overnight are vulnerable. Rodents contaminate air filters, cabin filters, and upholstery. (Pest management industry data)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Urgent pest control services", defaultAmount: 800, icon: "🚨",
        rationale: "Emergency treatments for dealership lots average $500–$1,500. Large lots with multiple buildings require zone-based treatment plans. (NPMA)" },
      { id: "insurance_claims", label: "Insurance Claims from Damage", description: "Vehicle warranty and insurance costs", defaultAmount: 3000, icon: "📋",
        rationale: "Comprehensive auto insurance may cover rodent damage, but dealer deductibles and claims processing increase costs. Warranty claims for pest damage are typically denied. (Insurance industry data)" },
      { id: "health_violations", label: "Health Violations in Service Area", description: "Shop area hygiene citations", defaultAmount: 1200, icon: "⚠️",
        rationale: "Service department break rooms and customer waiting areas are subject to health inspections. Rodent evidence in food service areas triggers fines. (OSHA, local health codes)" },
    ],
  },

  gym_fitness: {
    id: "gym_fitness",
    name: "Gym / Fitness Center",
    icon: "💪",
    color: "#059669",
    description: "Member cancellations, health violations, and facility issues",
    categories: [
      { id: "member_cancellations", label: "Member Complaints & Cancellations", description: "Lost memberships from pest sightings", defaultAmount: 2500, icon: "👥",
        rationale: "Average gym membership is $50–$75/mo. Losing 30–50 members from a pest incident = $1,500–$3,750/mo. Many contracts include hygiene escape clauses. (IHRSA industry data)" },
      { id: "health_violations", label: "Health Department Violations", description: "Gym facility inspection fines", defaultAmount: 2000, icon: "⚠️",
        rationale: "Gym and pool facilities are subject to health department inspections. Fines for pest-related violations range $200–$2,000. Some jurisdictions require posted inspection grades. (Local health departments)" },
      { id: "facility_issues", label: "Locker Room / Shower Issues", description: "Pest issues in wet areas and changing rooms", defaultAmount: 1200, icon: "🚿",
        rationale: "Moisture-rich locker rooms attract cockroaches, silverfish, and drain flies. Treatment requires overnight closure and specialized products. Member complaints peak in these areas. (NPMA)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Reactive pest control services", defaultAmount: 600, icon: "🚨",
        rationale: "Emergency gym treatments cost $400–$1,000. Must be done after hours to avoid member exposure. Large facilities need multi-zone treatment. (NPMA)" },
      { id: "brand_damage", label: "Brand Reputation Damage", description: "Social media and review impact", defaultAmount: 3000, icon: "📉",
        rationale: "Gym pest sightings generate viral social media content. One cockroach photo posted to Google reviews can drive away hundreds of potential members. (Social media impact studies)" },
      { id: "staff_complaints", label: "Staff Complaints", description: "Employee dissatisfaction and turnover", defaultAmount: 800, icon: "🔄",
        rationale: "Personal trainers and group fitness instructors are independent contractors who will move to competing gyms if conditions are poor. Replacement cost: $1,000–$3,000 per trainer. (IHRSA)" },
    ],
  },

  salon_spa: {
    id: "salon_spa",
    name: "Salon / Spa",
    icon: "💇",
    color: "#EC4899",
    description: "Client loss, health violations, and review damage",
    categories: [
      { id: "client_loss", label: "Client Loss from Pest Sightings", description: "Clients who never return after seeing pests", defaultAmount: 3500, icon: "👥",
        rationale: "Average salon client spends $50–$150 per visit, 6–12x/year. Losing 5–10 clients permanently = $3,000–$18,000/yr in lost revenue. Intimate service settings make pest sightings especially damaging. (PBA)" },
      { id: "health_violations", label: "Health Code Violations", description: "Cosmetology board and health department fines", defaultAmount: 2500, icon: "⚠️",
        rationale: "State cosmetology boards conduct regular inspections. Pest evidence can result in fines, license suspension, or mandatory closure until remediated. Fines range $500–$5,000. (State cosmetology boards)" },
      { id: "online_reviews", label: "Online Review Damage", description: "Lost new clients from pest-related reviews", defaultAmount: 4000, icon: "⭐",
        rationale: "86% of salon clients check online reviews before booking. One pest-related review can reduce new client bookings 20–30%. Salons depend heavily on Google/Yelp reputation. (BrightLocal survey)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Reactive pest control services", defaultAmount: 600, icon: "🚨",
        rationale: "Emergency salon treatments cost $300–$800. Must use products safe around cosmetic supplies and chemicals. After-hours service required. (NPMA)" },
      { id: "product_contamination", label: "Product Contamination", description: "Damaged or contaminated supplies", defaultAmount: 1200, icon: "🧴",
        rationale: "Pest contamination of open products, towels, and wax requires immediate disposal. Professional-grade products cost $20–$100+ per item. Full inventory contamination events cost $1,000–$5,000. (PBA)" },
      { id: "staff_turnover", label: "Staff Turnover", description: "Stylists leaving due to conditions", defaultAmount: 1000, icon: "🔄",
        rationale: "Experienced stylists are in high demand and will leave for better environments. Recruiting and training a replacement costs $5,000–$10,000. Lost clients who follow their stylist compounds the loss. (PBA, salon industry data)" },
    ],
  },

  single_family_residential: {
    id: "single_family_residential",
    name: "Single Family Residential",
    icon: "🏠",
    color: "#10B981",
    description: "Structural damage, health risks, and property value decline",
    categories: [
      { id: "structural_damage", label: "Structural Damage", description: "Foundation, framing, and insulation damage", defaultAmount: 250, icon: "🏠",
        rationale: "Termites cause $5B in damage to US homes annually, affecting 600,000 homes. Average repair: $3,000 ($250/mo). Repairs range from $1,000 to $37,500 for major structural work. Not covered by homeowner insurance. (Orkin, USDA, Angi)" },
      { id: "health_risks", label: "Health Risks to Family", description: "Allergies, asthma triggers, and disease exposure", defaultAmount: 150, icon: "🏥",
        rationale: "Cockroach allergens trigger asthma in 23–60% of urban children. Rodents carry 35+ diseases. Dust mites, cockroach droppings, and rodent urine are top indoor allergens. (NIH, CDC, EPA)" },
      { id: "property_value", label: "Property Value Decline", description: "Reduced home value and sale difficulty", defaultAmount: 400, icon: "📉",
        rationale: "Homes with termite history sell for 3–5% less. On a $400K home, that's $12,000–$20,000 ($1,000–$1,667/yr). 20% property value decrease reported in severe cases. (Orkin, real estate studies)" },
      { id: "food_contamination", label: "Food Contamination", description: "Pantry items destroyed by pests", defaultAmount: 100, icon: "🥫",
        rationale: "Average US household spends $500/mo on groceries. Pantry pests (Indian meal moths, weevils) can contaminate 10–25% of stored dry goods. Mice contaminate far more food than they eat. (USDA)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Reactive pest control at premium pricing", defaultAmount: 150, icon: "🚨",
        rationale: "Emergency residential treatments cost $150–$500 vs $40–$80 for scheduled quarterly service. Termite treatments run $250–$2,500 for the home. Prevention plans cost $300–$800/yr. (NPMA, Angi)" },
      { id: "medical_costs", label: "Allergic Reactions & Medical Costs", description: "Doctor visits, medications, and treatment", defaultAmount: 200, icon: "💊",
        rationale: "Average asthma-related ER visit: $1,502. Ongoing asthma medications: $100–$300/mo. Pest-related allergic reactions can require antihistamines, inhalers, and specialist visits. (CDC, American Lung Association)" },
    ],
  },

  other: {
    id: "other",
    name: "Other",
    icon: "🏗️",
    color: "#6B7280",
    description: "General pest-related costs for any property type",
    categories: [
      { id: "general_damage", label: "General Pest Damage", description: "Physical damage to property and materials", defaultAmount: 2000, icon: "🔧",
        rationale: "US spends $5B+ annually on termite damage alone. Rodents cause additional billions in wiring, insulation, and structural damage. (USDA, NPMA)" },
      { id: "health_violations", label: "Health & Safety Violations", description: "Regulatory fines and citations", defaultAmount: 2000, icon: "⚠️",
        rationale: "Fines range from $200 for minor citations to $125,000+ for healthcare facilities with immediate jeopardy violations. (FDA, CMS, local health departments)" },
      { id: "complaints", label: "Customer / Client Complaints", description: "Lost business from pest incidents", defaultAmount: 2000, icon: "👥",
        rationale: "5–9% revenue loss from negative reviews. One negative review costs $38/room/night for hotels. Customer trust is difficult and expensive to rebuild. (Harvard Business School, ScienceDirect)" },
      { id: "emergency_treatment", label: "Emergency Treatment Costs", description: "Reactive pest control at premium rates", defaultAmount: 800, icon: "🚨",
        rationale: "Emergency treatments cost 2–3x scheduled service rates. Average emergency call: $500–$1,500 commercial, $150–$500 residential. (NPMA)" },
      { id: "property_damage", label: "Property Damage", description: "Structural and cosmetic repairs", defaultAmount: 1500, icon: "🏠",
        rationale: "Termite repairs average $3,000. Rodent wiring repairs: $500–$5,000. Insulation replacement: $1,000–$3,000. Most property insurance excludes pest damage. (Angi, NPMA)" },
      { id: "legal_liability", label: "Legal Liability", description: "Lawsuit exposure and legal fees", defaultAmount: 5000, icon: "⚖️",
        rationale: "Pest-related lawsuits range from $2,000 small claims to $2M+ jury verdicts. Hotel bed bug settlements: $10K–$80K typical. Healthcare: $50K–$500K. Legal defense alone costs $5K–$25K. (Court records)" },
    ],
  },
};

/** Ordered array of industry IDs for display */
export const INDUSTRY_ORDER = [
  "restaurant_food_service",
  "hotel_hospitality",
  "multi_family_apartment",
  "healthcare_medical",
  "warehouse_distribution",
  "office_corporate",
  "retail_sales_floor",
  "education_school",
  "gym_fitness",
  "salon_spa",
  "auto_dealership",
  "church_worship",
  "single_family_residential",
  "other",
];
